# a=["grapes","orange",3,False,"akash",35]
# print(a)
# a.append("rohit")
# print(a)
# a.pop(2)
# print(a)
# a.insert(6,"shriwastav")
# print(a)
# a.remove(False)
# print(a)

# a=(1,2,3,4,5)
# print(type(a))
# a=()
# print(type(a))
# a=(1,)
# print(type(a))
